//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "analysis")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "idPatient")]
    pub id_patient: Option<Uuid>,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub velocity: Decimal,
    #[sea_orm(column_type = "Float")]
    pub velocity_diff: f32,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub time: Decimal,
    #[sea_orm(column_type = "Float")]
    pub time_diff: f32,
    pub steps: i32,
    #[sea_orm(column_type = "Float")]
    pub steps_diff: f32,
    pub cadence: i32,
    #[sea_orm(column_type = "Float")]
    pub cadence_diff: f32,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub bounce: Decimal,
    #[sea_orm(column_type = "Float")]
    pub bounce_diff: f32,
    #[sea_orm(column_name = "timeToUp", column_type = "Decimal(Some((4, 2)))")]
    pub time_to_up: Decimal,
    #[sea_orm(column_name = "timeToUp_diff", column_type = "Float")]
    pub time_to_up_diff: f32,
    pub date: Date,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "id_patient",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub patients: BelongsTo<Option<super::patients::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
