//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "metrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "minAge")]
    pub min_age: i32,
    #[sea_orm(column_name = "maxAge")]
    pub max_age: i32,
    #[sea_orm(column_name = "isMale")]
    pub is_male: bool,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub velocity: Decimal,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub time: Decimal,
    pub steps: i32,
    pub cadence: i32,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))")]
    pub bounce: Decimal,
    #[sea_orm(column_name = "timeToUp", column_type = "Decimal(Some((4, 2)))")]
    pub time_to_up: Decimal,
}

impl ActiveModelBehavior for ActiveModel {}
