//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "patients_remedies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "idPatient")]
    pub id_patient: Uuid,
    #[sea_orm(column_name = "idRemedy")]
    pub id_remedy: Uuid,
    pub quantity: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "id_patient",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub patients: BelongsTo<super::patients::Entity>,
    #[sea_orm(
        belongs_to,
        from = "id_remedy",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub remedies: BelongsTo<super::remedies::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
