//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PatientBloodType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "patients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub birthdate: Date,
    #[sea_orm(column_name = "isMale")]
    pub is_male: bool,
    #[sea_orm(column_name = "bloodType")]
    pub blood_type: PatientBloodType,
    #[sea_orm(column_name = "idUser")]
    pub id_user: Uuid,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub analyses: HasMany<super::analysis::Entity>,
    #[sea_orm(has_many)]
    pub patients_remedies: HasMany<super::patients_remedies::Entity>,
    #[sea_orm(
        belongs_to,
        from = "id_user",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
