//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "patient_blood_type")]
pub enum PatientBloodType {
    #[sea_orm(string_value = "a_positive")]
    APositive,
    #[sea_orm(string_value = "a_negative")]
    ANegative,
    #[sea_orm(string_value = "b_positive")]
    BPositive,
    #[sea_orm(string_value = "b_negative")]
    BNegative,
    #[sea_orm(string_value = "ab_positive")]
    AbPositive,
    #[sea_orm(string_value = "ab_negative")]
    AbNegative,
    #[sea_orm(string_value = "o_positive")]
    OPositive,
    #[sea_orm(string_value = "o_negative")]
    ONegative,
}
